(function($) {
    $(document).ready(function() {
	
	$('#bm_plot').scianimator({
	    'images': ['images/bm_plot1.png', 'images/bm_plot2.png', 'images/bm_plot3.png', 'images/bm_plot4.png', 'images/bm_plot5.png', 'images/bm_plot6.png', 'images/bm_plot7.png', 'images/bm_plot8.png', 'images/bm_plot9.png', 'images/bm_plot10.png', 'images/bm_plot11.png', 'images/bm_plot12.png', 'images/bm_plot13.png', 'images/bm_plot14.png', 'images/bm_plot15.png', 'images/bm_plot16.png', 'images/bm_plot17.png', 'images/bm_plot18.png', 'images/bm_plot19.png', 'images/bm_plot20.png', 'images/bm_plot21.png', 'images/bm_plot22.png', 'images/bm_plot23.png', 'images/bm_plot24.png', 'images/bm_plot25.png', 'images/bm_plot26.png', 'images/bm_plot27.png', 'images/bm_plot28.png', 'images/bm_plot29.png', 'images/bm_plot30.png', 'images/bm_plot31.png', 'images/bm_plot32.png', 'images/bm_plot33.png', 'images/bm_plot34.png', 'images/bm_plot35.png', 'images/bm_plot36.png', 'images/bm_plot37.png', 'images/bm_plot38.png', 'images/bm_plot39.png', 'images/bm_plot40.png', 'images/bm_plot41.png', 'images/bm_plot42.png', 'images/bm_plot43.png', 'images/bm_plot44.png', 'images/bm_plot45.png', 'images/bm_plot46.png', 'images/bm_plot47.png', 'images/bm_plot48.png', 'images/bm_plot49.png', 'images/bm_plot50.png', 'images/bm_plot51.png', 'images/bm_plot52.png', 'images/bm_plot53.png', 'images/bm_plot54.png', 'images/bm_plot55.png', 'images/bm_plot56.png', 'images/bm_plot57.png', 'images/bm_plot58.png', 'images/bm_plot59.png', 'images/bm_plot60.png', 'images/bm_plot61.png', 'images/bm_plot62.png', 'images/bm_plot63.png', 'images/bm_plot64.png', 'images/bm_plot65.png', 'images/bm_plot66.png', 'images/bm_plot67.png', 'images/bm_plot68.png', 'images/bm_plot69.png', 'images/bm_plot70.png', 'images/bm_plot71.png', 'images/bm_plot72.png', 'images/bm_plot73.png', 'images/bm_plot74.png', 'images/bm_plot75.png', 'images/bm_plot76.png', 'images/bm_plot77.png', 'images/bm_plot78.png', 'images/bm_plot79.png', 'images/bm_plot80.png', 'images/bm_plot81.png', 'images/bm_plot82.png', 'images/bm_plot83.png', 'images/bm_plot84.png', 'images/bm_plot85.png', 'images/bm_plot86.png', 'images/bm_plot87.png', 'images/bm_plot88.png', 'images/bm_plot89.png', 'images/bm_plot90.png', 'images/bm_plot91.png', 'images/bm_plot92.png', 'images/bm_plot93.png', 'images/bm_plot94.png', 'images/bm_plot95.png', 'images/bm_plot96.png', 'images/bm_plot97.png', 'images/bm_plot98.png', 'images/bm_plot99.png', 'images/bm_plot100.png'],
	    'width': 480,
	    'delay': 50,
	    'loopMode': 'loop'
	});
	$('#bm_plot').scianimator('play');
    });
})(jQuery);
