---
title: "Music Descriptors Supplementary materials"
author: "Brendon Mizener"
date: "3/29/2021"
output: 
   pdf_document:
      keep_tex: TRUE
      includes: 
         in_header:  
             - "musdes_sup_preamble.tex"

---

```{r setup, include = FALSE}
# Seed for random number generation
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message=FALSE, fig.align = "center",cache.extra = knitr::rand_seed, dev = c("pdf", "png"))
set.seed(42)

papaja::r_refs("r-references.bib")
```

```{r analysis-preferences}
library("papaja")
library(ExPosition)
library(InPosition)
library(MExPosition)
library(PTCA4CATA)
library(purrr)
library(plyr)
library(tidyverse)
library(readxl)
library(stringr)
library(stringi)
library(rlist)
library(wesanderson)
library(kableExtra)
library(ggplotify)
library(gridExtra)
library(grid)
library(abind)
library(apaTables)
library(pander)
library(flextable)
```

```{R graphPath}
powerpointFilename <- 'Music-Descriptor-Supp.pptx'
path2pptx    <- './Analysis/'
name4Graphs  <- paste0(path2pptx,powerpointFilename)
title4Graphs <- 'Music Descriptors Supp '
```

Supplementary materials for "Cognitive Music Listening Space: A Multivariate Approach". Additional material, including stimulus examples and datasets can be found at github.com/brendonmiz/musicdescriptors_supp.


# Supplementary Materials: Experiment 1

```{=latex}

\begin{lltable}
\begin{footnotesize}
\begin{longtable}{p{0.2\textwidth}p{0.2\textwidth}p{0.2\textwidth}p{0.2\textwidth}p{0.2\textwidth}p{0.2\textwidth}}\noalign{\getlongtablewidth\global\LTcapwidth=\longtablewidth}
\caption{\label{tab:qualitiestable}Musical Qualities and the provided survey response options, English.}\\
\toprule[.8pt]
 \multicolumn{1}{c}{Harmonic Material} & \multicolumn{1}{c}{Tempo} & \multicolumn{1}{c}{Meter} & \multicolumn{1}{c}{Density} & \multicolumn{1}{c}{Genre} & \multicolumn{1}{c}{Articulation}\\
 \midrule
      Diatonic: Major & Very slow & Simple Duple & Very sparse & Baroque & Staccato \\
      Diatonic: Minor & Slow & Simple Triple & Moderately sparse & Classical & Marcato \\
      Blues & Moderately Slow & Simple Quadruple  & More sparse than dense & Romantic & Legato\\
      Chromatic & Moderate & Compound Duple & More dense than sparse & Impressionist & Tenuto\\
      Whole tone & Moderately Fast & Compound Triple & Moderately Dense & Modern & Other \\       
      Modal  & Fast & Compound Quadruple & Very Dense & Jazz/Blues & \\
      Quintal/Quartal  & Very Fast & Complex & & Contemporary & \\
      Ambiguous  & & & & Other & \\
      Other  & & & & & \\
\bottomrule\addlinespace[.5em]
 & \multicolumn{1}{c}{Contour} & \multicolumn{1}{c}{Motion} & \multicolumn{1}{c}{Range} & \multicolumn{1}{c}{Dynamics} & \\
 \cmidrule[.5pt]{2-5}
  & Ascending & Conjunct & Narrow & Soft & \\
  & Descending & Disjunct & Moderate & Moderate  & \\
  & Arch & \multirow{2}{0.2\textwidth}{Combination of conjunct and disjunct} & Wide & Loud  & \\
  & Undulating &  & Very Wide & Varied: gradual crescendo &\\
  & Pendulum & \multirow{2}{0.2\textwidth}{I do not think this excerpt has a melody} & \multirow{2}{0.2\textwidth}{I do not think this excerpt has a melody} & \multirow{2}{0.2\textwidth}{Varied: gradual decrescendo} &\\
  & Terrace & & & & \\
  & \multirow{2}{0.2\textwidth}{I do not think this excerpt has a melody} & Other & & \multirow{2}{0.2\textwidth}{Some of each, soft and loud}  &\\
  & & & & & \\
  & Other & & & Other & \\
  
\cmidrule[.75pt]{2-5}
\end{longtable}
\end{footnotesize}
\end{lltable}
```

```{=latex}

\begin{lltable}
\begin{footnotesize}
\begin{longtable}{p{0.2\textwidth}p{0.2\textwidth}p{0.25\textwidth}p{0.2\textwidth}p{0.2\textwidth}p{0.15\textwidth}}\noalign{\getlongtablewidth\global\LTcapwidth=\longtablewidth}
\caption{\label{tab:qualitiestablefr}Musical Qualities and the provided survey response options, French.}\\
\toprule[.8pt]
 \multicolumn{1}{c}{Harmonie} & \multicolumn{1}{c}{Vitesse} & \multicolumn{1}{c}{Mesure} & \multicolumn{1}{c}{Densité} & \multicolumn{1}{c}{Genre} & \multicolumn{1}{c}{Articulation}\\
 \midrule
      Diatonique: majeur & Très lente & Mesure simple, deux temps & Très épurée & Baroque & Staccato \\
      Diatonique: mineur & Lente & Mesure simple, trois temps & Modérément épurée & Classique & Marcato \\
      Gamme Blues & Moyennement lent & Mesure simple, quatre temps & Plutôt épurée que dense & Romantique & Legato\\
      Chromatique & Moyenne & Mesure composée, deux temps & Plutôt dense qu’épurée & Impressioniste & Tenuto\\
      Gamme par ton & Moyennement rapide & Mesure composée, trois temps & Moyennement dense & Moderne & Autre (précisez) \\       
      Modal  & Rapide & Mesure composée, quatre temps & Très dense & Jazz-Blues & \\
      Ambigu  & Très rapide & Mesure complexe & & Contemporarain & \\
      \multirow{2}{0.2\textwidth}{Je ne pense pas que cet extrait ait une mélodie}  & & & & Autre (précisez) & \\
        & & & & & \\
      Autre (précisez)  & & & & & \\
\bottomrule\addlinespace[.5em]
 & \multicolumn{1}{c}{Contour} & \multicolumn{1}{c}{Mouvement} & \multicolumn{1}{c}{Ambitus} & \multicolumn{1}{c}{Dynamiques} & \\
 \cmidrule[.5pt]{2-5}
  & Ascendant & Conjoint & Ambitus resserré & Doux & \\
  & Descendant & Disjoint & Ambitus modéré & Moyen  & \\
  & Forme en arche & \multirow{2}{0.2\textwidth}{Une combinaison de conjoint et disjoint} & Ambitus grand & Fort  & \\
  & Petites vagues successives &  & Ambitus très grand & \multirow{2}{0.2\textwidth}{Varié : crescendo progressif} &\\
  & \multirow{2}{0.2\textwidth}{Grandes vagues successives} & \multirow{2}{0.2\textwidth}{Je ne pense pas que cet extrait ait une mélodie} & \multirow{2}{0.2\textwidth}{Je ne pense pas que cet extrait ait une mélodie} & &\\
  &   & & & \multirow{2}{0.2\textwidth}{Varié : decrescendo progressif}  & \\
  & \multirow{2}{0.2\textwidth}{Plusieurs phases descendantes successives} & Autre (précisez) & &  &\\
  & & & & \multirow{2}{0.2\textwidth}{Un peu des deux: doux et fort} & \\
  & \multirow{2}{0.2\textwidth}{Je ne pense pas que cet extrait ait une mélodie} & & &  & \\
  &  & & & Autre (précisez) & \\
  & Autre (précisez) & & &  & \\
  
\cmidrule[.75pt]{2-5}
\end{longtable}
\end{footnotesize}
\end{lltable}
```

```{r qual4sup}

load("catadatamusdim.RData")
musdimdata <- catadata.list$contingency[,order(colnames(catadata.list$contingency))]
numberofdims <- catadata.list$numberofdims[order(names(catadata.list$numberofdims))]
thebrick <- catadata.list$thebrick[,order(colnames(catadata.list$contingency)),]


rows2drop <- c(6,14) 

musdimdata.no6 <- musdimdata[-rows2drop,]
thebrick.no6 <- thebrick[-rows2drop,,]
```

```{r Q.parts.sup}

# reorder some of the columns in the french experts dataset, 
# taking only the ones we want to analyse for now
fr.ex.data <- catadata.list$french.expert.data[c(1:3,6,7,9:12),c(1,4,5,6,7)]
colnames(fr.ex.data) <- c("age", "gen", "nat", "tr_yrs", "tr_type")
fr.ex.data$gen[which(fr.ex.data$gen == "Homme")] <- "M"
fr.ex.data$gen[which(fr.ex.data$gen == "Femme")] <- "F"
fr.ex.data$nat <- "France"
fr.ex.data$tr_type[which(fr.ex.data$tr_type == "Instrumentale")] <- "Inst"
fr.ex.data$tr_type[which(fr.ex.data$tr_type == "Vocale")] <- "Voc"

am.ex.data <- catadata.list$expert.data[,c(1:3,6,7)]
colnames(am.ex.data) <- colnames(fr.ex.data)
am.ex.data$nat <- "US"
am.ex.data$gen[which(am.ex.data$gen == "Male")] <- "M"
am.ex.data$gen[which(am.ex.data$gen == "Female")] <- "F"
am.ex.data$tr_type[which(am.ex.data$tr_type == "Instrumental")] <- "Inst"
am.ex.data$tr_type[which(am.ex.data$tr_type == "Vocal")] <- "Voc"

# Bind it all together
ex.data <- rbind(am.ex.data, fr.ex.data)

bygender <- as.factor(ex.data$gen)
bynationality <- as.factor(ex.data$nat)

```

```{r Q.ca.sup, cache = T, message=FALSE, warning=FALSE, include = FALSE}

dimcares.inf <- epCA.inference.battery(musdimdata.no6, 
                 masses= NULL, weights= NULL, 
                 hellinger = FALSE, symmetric = TRUE, 
                 graphs =FALSE, test.iters = 1000)

# Factor Scores
FIsym  <- dimcares.inf$Fixed.Data$ExPosition.Data$fi*-1
FJs    <- dimcares.inf$Fixed.Data$ExPosition.Data$fj*-1
CA.Q.Eigs <- dimcares.inf$Fixed.Data$ExPosition.Data$eigs
CA.Q.pEig <- dimcares.inf$Inference.Data$components$eigs.perm
```

```{r someQcolors.sup}
col4M <- wes_palettes$Zissou1[1]
col4F <- wes_palettes$Zissou1[5]
col4FR <- wes_palettes$Darjeeling2[2]
col4AM <- wes_palettes$Darjeeling1[1]
# 
col4byG <- as.character(bygender)
col4byG[col4byG == "F"] <- col4F
col4byG[col4byG == "M"] <- col4M



col4byN <- as.character(bynationality)

col4byN[col4byN == "France"] <- col4FR
col4byN[col4byN == "US"] <- col4AM

#bynationality[bynationality == "FR"] <- 'France'
#bynationality[bynationality == "AM"] <- "US"


col4cols <- wes_palette("FantasticFox1", 
                        length(numberofdims), type = "continuous")
col4cols <- rep(col4cols, numberofdims)


```

```{r ca4Judges}
# We have a problem here because most matrices
#  have lines with zeros. A symmetric difference matrix 
#  would do better than an RV or a 
#  chi2 distance so we use createSymDist4PTCA

Cmat <- createSymDist4PTCA(thebrick)$CrossProduct

# Calculate the eigenvalues and the percentage of variance extracted (tau)
eigenCmat <- eigen(Cmat, symmetric = TRUE)
eig4Cmat <-  eigenCmat$values
tau4Cmat <- round( (100*eig4Cmat) / sum(eig4Cmat))

# Calculate factor scores for the first three dimensions
nk       <- 3
F4Cmat   <- eigenCmat$vectors[,1:nk] %*% diag(eig4Cmat[1:nk]^(1/2))

# Prep for plotting
Shortnames4Participants <-  dimnames(thebrick[[3]])
rownames(F4Cmat) <- Shortnames4Participants

# Make labels
labels4RV <- createxyLabels.gen(1,2,lambda = eig4Cmat, tau = tau4Cmat)
```

```{r bootQCA.sup, cache=TRUE}

bootCA <- Boot4PTCA(ZeDataCube = thebrick.no6,
           fi = FIsym,
           fj = FJs,
           eigs = CA.Q.Eigs,
           nf2keep = 3,
           nBootIter = 500)
# Compute Bootstrapped ratios
bootRatios.I <- PTCA4CATA::boot.ratio.test(bootCA$RowsBoot,
                                            critical.value = 2)
bootRatios.J <- PTCA4CATA::boot.ratio.test(bootCA$ColumnsBoot,
                                              critical.value = 2)
# Probabilities 
probBR.I  <- bootRatios.I$prob.boot.ratios
probBR.J  <- bootRatios.J$prob.boot.ratios
```

```{r screeRV, fig.height = 4, fig.width = 8, fig.align='center', include = FALSE}
# Scree plot with significance
ScreeInf <- PlotScree(ev = eig4Cmat,
                      max.ev = NULL, alpha = 0.05,
                      col.ns = "#006D2C",
                      title = " ")
a000.00.screeRV <-  recordPlot()

scree4qsup <- recordPlot()

```

```{r basemaps}

BaseMap.Nationality <- createFactorMap(X = F4Cmat ,
                              axis1 = 1, axis2 = 2,
                              display.points = TRUE,
                              col.points = col4byN,
                              pch = 19, cex = 2.5, 
                              title = "Colored according to Nationality",
                              display.labels = TRUE,
                              col.labels = col4byN,
                              text.cex = 4, font.face = "bold",
                              font.family = "sans",
                              col.axes = "darkorchid",
                              alpha.axes = 0.2,
                              width.axes = 1.1,
                              col.background = adjustcolor("lavender",
                                                       alpha.f = 0.2),
                              force = 1, segment.size = 3)

BaseMap.Gender <- createFactorMap(X = F4Cmat ,
                              axis1 = 1, axis2 = 2,
                              display.points = TRUE,
                              col.points = col4byG,
                              pch = 19, cex = 2.5,
                              title = "Colored according to Gender",
                              display.labels = TRUE,
                              col.labels = col4byG,
                              text.cex = 4, font.face = "bold",
                              font.family = "sans",
                              col.axes = "darkorchid",
                              alpha.axes = 0.2,
                              width.axes = 1.1,
                              col.background = adjustcolor("lavender",
                                                       alpha.f = 0.2),
                              force = 1, segment.size = 3)
```


```{r means4graphs}
gendermeans <- getMeans(F4Cmat, bygender)
nationmeans <- getMeans(F4Cmat, bynationality)

BootCube.N <- PTCA4CATA::Boot4Mean(F4Cmat, design = bynationality,
                      niter = 100,
                      suppressProgressBar = TRUE)
dimnames(BootCube.N$BootCube)[[2]] <- paste0('Dimension ',
                                             1: dim(BootCube.N$BootCube)[[2]])

BootCube.G <- PTCA4CATA::Boot4Mean(F4Cmat, design = bygender,
                      niter = 100,
                      suppressProgressBar = TRUE)
dimnames(BootCube.G$BootCube)[[2]] <- paste0('Dimension ',
                                             1: dim(BootCube.G$BootCube)[[2]])
```



```{r ellipses, echo = TRUE}
n.ellipse <- MakeCIEllipses(BootCube.N$BootCube[,1:2,], 
                            names.of.factors = c("Dimension 1","Dimension 2"),
                            col = c(col4AM, col4FR))
g.ellipse <- MakeCIEllipses(BootCube.G$BootCube[,1:2,], 
                            names.of.factors = c("Dimension 1","Dimension 2"),
                            col = c(col4M, col4F))
```


```{r}
n.symdist.means <- createFactorMap(nationmeans,
                              axis1 = 1, axis2 = 2, 
                              title = " ",
                              col.points =  c(col4AM, col4FR),
                              alpha.points = 1, # no transparency
                              constraints = BaseMap.Nationality$constraints,
                              display.points = TRUE,
                              pch = 19, cex = 5,
                              display.labels = TRUE,
                              col.labels = c(col4AM, col4FR), 
                              text.cex = 4,font.face = "bold",
                              font.family = "sans", col.axes = "darkorchid", 
                              alpha.axes = 0.2, width.axes = 1.1, 
                              col.background = adjustcolor("lavender", alpha.f = 0.2), 
                              force = 1, segment.size = 0)

g.symdist.means <- createFactorMap(gendermeans,
                              axis1 = 1, axis2 = 2, 
                              title = " ",
                              col.points =  c(col4M, col4F),
                              alpha.points = 1, # no transparency
                              constraints = BaseMap.Gender$constraints,
                              display.points = TRUE,
                              pch = 19, cex = 5,
                              display.labels = TRUE,
                              col.labels = c(col4M, col4F), 
                              text.cex = 4,font.face = "bold",
                              font.family = "sans", col.axes = "darkorchid", 
                              alpha.axes = 0.2, width.axes = 1.1, 
                              col.background = adjustcolor("lavender", alpha.f = 0.2), 
                              force = 1, segment.size = 0)

a.01.map4part <- BaseMap.Nationality$zeMap_background + labels4RV +
                  BaseMap.Nationality$zeMap_dots +
                  n.symdist.means$zeMap_text + 
                    n.symdist.means$zeMap_dots + n.ellipse + ggtitle("Colored according to nationality") + theme(plot.title = element_text(size = 14, family = "serif"),
                      axis.title = element_text(size = 12, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 12, face = "italic", family = "serif"))

a.02.map4part <- BaseMap.Gender$zeMap_background + labels4RV +
                  BaseMap.Gender$zeMap_dots + g.symdist.means$zeMap_text +
                    g.symdist.means$zeMap_dots + g.ellipse  + ggtitle("Colored according to gender") + theme(plot.title = element_text(size = 14, family = "serif"),
                      axis.title = element_text(size = 12, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 12, face = "italic", family = "serif"))
```

```{r printRVbydesign, echo = true, fig.width=10,figure.show = 'hold'}
grid.arrange(as.grob(a.01.map4part), 
             as.grob(a.02.map4part), ncol = 2)

rv4qsup <- recordPlot()

```



```{r HCA}

fisym1 <- FIsym
rownames(fisym1) <- c(1:5,7:13,15:30)

D <- dist(fisym1, method = "euclidean")
fit <- hclust(D, method = "ward.D2")

ngroups <- 4

col4extree <- wes_palette("Darjeeling1", ngroups, type = "continuous")
 
ex.groups <- cutree(fit, k= ngroups)

col4exgrp <- recode(ex.groups, 
                    "1" = col4extree[1],
                    "2" = col4extree[2],
                    "3" = col4extree[3],
                    "4" = col4extree[4],
                    )

col4extree <- col4exgrp[fit$order]

mus.tree4excerpts <- factoextra::fviz_dend(fit,  k = ngroups, 
                        k_colors = unique(col4extree), 
                        label_cols = col4extree,
                        cex = .75, xlab = 'Excerpts',
                        main = ' ', 
                        rect = TRUE, rect_fill = TRUE) + theme(plot.title = element_text(size = 14, family = "serif"),
                      axis.title = element_text(size = 12, face = "italic", family = "serif"))
                      
 
print(mus.tree4excerpts)

hcatreesup <- recordPlot()


```
```{r HCAW6}
caresw6 <- epCA(musdimdata, graphs = FALSE)

rownames(caresw6$ExPosition.Data$fi) <- c(1:30)

D <- dist(caresw6$ExPosition.Data$fi, method = "euclidean")
fit.w6 <- hclust(D, method = "ward.D2")

ngroups <- 6

col4extree <- wes_palette("Darjeeling1", ngroups, type = "continuous")
 
ex.groups <- cutree(fit.w6, k= ngroups)

col4exgrp.w6 <- recode(ex.groups, 
                    "1" = col4extree[1],
                    "2" = col4extree[2],
                    "3" = col4extree[3],
                    "4" = col4extree[4],
                    "5" = col4extree[5],
                    "6" = col4extree[6]
                    )

col4extree.w6 <- col4exgrp.w6[fit.w6$order]

mus.tree4excerpts.w6 <- factoextra::fviz_dend(fit.w6,  k = ngroups, 
                        k_colors = unique(col4extree.w6), 
                        label_cols = col4extree.w6,
                        cex = .75, xlab = 'Excerpts',
                        main = ' ', 
                        rect = TRUE, rect_fill = TRUE)  + theme(plot.title = element_text(size = 14, family = "serif"),
                      axis.title = element_text(size = 12, face = "italic", family = "serif"))
 
print(mus.tree4excerpts.w6)

hcatreeqw6sup <- recordPlot()

```



```{r excerptsmaps23, fig.height=8}

axisone <- 1
axistwo <- 2

labelsforexcerpts12 <- createxyLabels(resCA = caresw6)
dertitel1 <- "Dimensions 1 and 2"

fiw614 <- caresw6$ExPosition.Data$fi*-1

rownames(fiw614)<- c(1:30)

Basemap.Q.12 <- createFactorMap(X = fiw614,
                                    axis1 = axisone,
                                    axis2 = axistwo, 
                                    col.points = col4exgrp.w6,
                                    display.points = T,
                                    pch = 19, cex = 2.5,
                                    display.labels = T,
                                    col.labels = col4exgrp.w6,
                                    text.cex = 4, font.face = "bold",
                                    font.family = "sans",
                                    col.axes = "darkorchid",
                                    alpha.axes = 0.2,
                                    width.axes = 1.1,
                                    col.background = adjustcolor("lavender",
                                                       alpha.f = 0.2),
                                    force = 1, segment.size = 3,
#                                    title = dertitel1
                                    )


groupvec <- fiw614[,1]
groupvec.Q <- data.frame(ex.groups)
groupvec.Q <- data.frame(abind(groupvec, groupvec.Q, along = 2))
groupvec.Q$ex.groups <- as.factor(groupvec.Q$ex.groups)

ti.q.12 <- MakeToleranceIntervals(data = data.frame(caresw6$ExPosition.Data$fi*-1), 
                                  design = as.factor(groupvec.Q$ex.groups), 
                                  col = unique(col4exgrp.w6))



mus.006 <- Basemap.Q.12$zeMap + labelsforexcerpts12 + ti.q.12 + theme(plot.title = element_text(size = 16, family = "serif"),
                      axis.title = element_text(size = 14, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 14, face = "italic", family = "serif"))
print(mus.006)


axisone = 3
dertitel2 <- "Dimensions 2 and 3"
labelsforexcerpts23 <- createxyLabels(resCA = caresw6, x_axis = axisone)
Basemap.Q.23 <- createFactorMap(X = fiw614,
                                axis1 = axisone,
                                axis2 = axistwo, 
                                col.points = col4exgrp.w6,
                                display.points = T,
                                pch = 19, cex = 2.5,
                                display.labels = T,
                                col.labels = col4exgrp.w6,
                                text.cex = 4, font.face = "bold",
                                font.family = "sans",
                                col.axes = "darkorchid",
                                alpha.axes = 0.2,
                                width.axes = 1.1,
                                col.background = adjustcolor("lavender",
                                                       alpha.f = 0.2),
                                force = 1, segment.size = 3,
#                                title = dertitel2,
                                )
ti.q.23 <- MakeToleranceIntervals(data = data.frame(caresw6$ExPosition.Data$fi*-1),
                                  axis1 = 3, axis2 = 2,
                                  design = as.factor(groupvec.Q$ex.groups), 
                                  col = unique(col4exgrp.w6))

mus.007 <- Basemap.Q.23$zeMap + labelsforexcerpts23 +ti.q.23+ theme(plot.title = element_text(size = 16, family = "serif"),
                      axis.title = element_text(size = 14, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 14, face = "italic", family = "serif"))

print(mus.007)

#grid.arrange(
#    as.grob(mus.006),as.grob(mus.007),
#    ncol = 2,nrow = 1, 
#    top = textGrob("Row Factor Scores Plots, Qualities Survey, Including Excerpts 6 and 14", gp = gpar(fontsize = 18, font = 1)), 
#    bottom = textGrob("Note: Colored according to the results of the Hierarchical Cluster Analysis", gp = gpar(fontsize = 12, font = 3))
# )

exmaps23sup <- recordPlot()

```

```{r colmaps, fig.height=10, out.width='100%'}

axisone <- 1
axistwo <- 2


mustau <- dimcares.inf$Fixed.Data$ExPosition.Data$pdq$tau
muslam <- dimcares.inf$Fixed.Data$ExPosition.Data$pdq$eigs


labelsforexcerpts <- createxyLabels.gen(axisone, axistwo,lambda = muslam, tau = mustau)

Basemap.cols <- createFactorMap(X = FJs,
                                    axis1 = axisone,
                                    axis2 = axistwo, 
                                    col.points = col4cols,
#                                    constraints = Basemap.excerpts$constraints,
#                                    title = "Column Factor Scores \nColored according to dimension group",
                                    display.points = T,
                                    pch = 19, cex = 4,
                                    display.labels = T,
                                    col.labels = col4cols,
                                    text.cex = 4, font.face = "italic",
                                    font.family = "sans",
                                    col.axes = "darkorchid",
                                    alpha.axes = 0.2,
                                    width.axes = 1.1,
                                    col.background = adjustcolor("lavender",
                                                       alpha.f = 0.2),
                                    force = 1, segment.size = 3
                                    )
                                    

mus.007 <- Basemap.cols$zeMap_background + labelsforexcerpts + Basemap.cols$zeMap_dots
mus.008 <- Basemap.cols$zeMap_background + labelsforexcerpts + Basemap.cols$zeMap_text
mus.009 <- Basemap.cols$zeMap + labelsforexcerpts + theme(plot.title = element_text(size = 16, family = "serif"),
                      axis.title = element_text(size = 14, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 14, face = "italic", family = "serif"))
print(mus.009)

colmaps4Qsup <- recordPlot()

```


```{r morecolmaps, fig.show = 'hold', out.width="50%", ncols = 2, fig.align="default"}
# This was originally initialized as something else. Instead of changing each
# instance, I'm just changing this one.
FJ.all <- FJs
#Initialize an empty list
FJ.split <- vector(mode = "list", length = length(numberofdims))

# Name the elements of the list with the names of each group of musical dimensions
names(FJ.split) <- names(numberofdims)

# This loop puts the factor scores for each group of musical dimensions 
# in each element of the list
for (i in 1:length(numberofdims)){
    FJ.split[[i]] = FJ.all[which(stri_startswith(rownames(FJ.all), 
                                                 coll = names(numberofdims)[i])), ]
    }

# We also need to do the same for the constraints
FJ.constraints <- vector(mode = "list", length = length(numberofdims))
names(FJ.constraints) = names(numberofdims)
axisone <- 1
axistwo <- 2

for (i in 1:length(numberofdims)){
    
  FJ.constraints[[i]] <- minmaxHelper(FJ.split[[i]], 
                                      axis1 = axisone, axis2 = axistwo)
}

# And finally we need to create a list for the actual maps
FJ.maps <- vector(mode = "list", length = length(numberofdims))
names(FJ.maps) = names(numberofdims)
# This loop uses the three lists we've created to create a set of maps, with one
# for each group of factor scores.


for (i in 1:length(numberofdims)){
  
  FJ.maps[[i]] <- createFactorMap(FJ.split[[i]],
                                  axis1 = axisone, axis2 = axistwo,
                                  constraints = Basemap.cols$constraints,
                                  col.points = unique(col4cols)[i],
                                    display.points = T,
                                    pch = 19, cex = 4,
                                    display.labels = T,
                                    col.labels = unique(col4cols)[i],
                                    text.cex = 4, font.face = "italic",
                                    font.family = "sans",
                                    col.axes = "darkorchid",
                                    alpha.axes = 0.2,
                                    width.axes = 1.1,
                                    col.background = adjustcolor("lavender",
                                                       alpha.f = 0.2),
                                    force = 1, segment.size = 3
                                    )
  print(FJ.maps[[i]]$zeMap + labelsforexcerpts)
}


```

```{r justsomecontsqsup}

signed.ctrI <- dimcares.inf$Fixed.Data$ExPosition.Data$ci * sign(FIsym)
signed.ctrJ <- dimcares.inf$Fixed.Data$ExPosition.Data$cj[-9,] * sign(FJs)[-9,]
```

```{r contributionsqsup, fig.width=16}
# plot contributions of rows for component 1
ctrI.1 <- PrettyBarPlot2(signed.ctrI[,1],
                         threshold = 1 / NROW(signed.ctrI),
                         font.size = 3,
                         color4bar = col4exgrp, # we need hex code
                         ylab = 'Contributions', #sortValues = TRUE,
                         ylim = c(1.2*min(signed.ctrI[,1]), 1.2*max(signed.ctrI[,1]))
) + ggtitle("Dimension 1", subtitle = 'Rows') + theme(plot.title = element_text(size = 16, family = "serif"),
                      axis.title = element_text(size = 14, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 14, face = "italic", family = "serif"))



# plot contributions of columns for component 1
ctrJ.1 <- PrettyBarPlot2(signed.ctrJ[,1],
                         threshold = 1 / NROW(signed.ctrJ),
                         font.size = 3,
                         color4bar = col4cols, # we need hex code
                         ylab = 'Contributions',
                         ylim = c(1.2*min(signed.ctrJ[,1]),1.2*max(signed.ctrJ[,1]))
) + ggtitle("Dimension 1", subtitle = 'Columns') + theme(plot.title = element_text(size = 16, family = "serif"),
                      axis.title = element_text(size = 14, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 14, face = "italic", family = "serif"))

# plot contributions of rows for component 2
ctrI.2 <- PrettyBarPlot2(signed.ctrI[,2],
                         threshold = 1 / NROW(signed.ctrI),
                         font.size = 3,
                         color4bar = col4exgrp, # we need hex code
                         ylab = 'Contributions',
                         ylim = c(1.2*min(signed.ctrI[,2]), 1.2*max(signed.ctrI[,2]))
) + ggtitle("Dimension 2", subtitle = 'Rows') + theme(plot.title = element_text(size = 16, family = "serif"),
                      axis.title = element_text(size = 14, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 14, face = "italic", family = "serif"))

# plot contributions of columns for component 2
ctrJ.2 <- PrettyBarPlot2(signed.ctrJ[,2],
                         threshold = 1 / NROW(signed.ctrJ),
                         font.size = 3,
                         color4bar = col4cols, # we need hex code
                         ylab = 'Contributions',
                         ylim = c(1.2*min(signed.ctrJ[,2]), 1.2*max(signed.ctrJ[,2]))
)+ ggtitle("Dimension 2", subtitle = 'Columns') + theme(plot.title = element_text(size = 16, family = "serif"),
                      axis.title = element_text(size = 14, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 14, face = "italic", family = "serif"))

grid.arrange(
    as.grob(ctrI.1),as.grob(ctrJ.1),
    as.grob(ctrI.2),as.grob(ctrJ.2),
    ncol = 2,nrow =2)
  

Ctr.IJ <- recordPlot()
```
# Supplementary Materials: Experiment 2

```{r Adatain}
load("adj.catadata.list.RData")
load("excerptsdesign.RData")
load("adjdesign.RData")
load("adjectivecolors.RData")

```

```{r A.CA}
adj.contingency <- adj.catadata.list$adjcontingency

adjsym.cares <- epCA(adj.contingency, 
                     symmetric = TRUE)

adjrenorm <- CARenormalization(adjsym.cares$ExPosition.Data$fi,
                               delta = adjsym.cares$ExPosition.Data$pdq$Dv,
                               singularValues = T,
                               masses = adjsym.cares$ExPosition.Data$M
                               )

FIsym.adj <- adjsym.cares$ExPosition.Data$fi
FIasym.adj <- adjrenorm$G_A
FJs.adj <- adjsym.cares$ExPosition.Data$fj
CAEigs.adj <- adjsym.cares$ExPosition.Data$eigs
```

```{r adjtable}

tr <- read_xlsx("translations.xlsx")

apa_table(tr, 
          caption = "CATA Adjectives", 
          placement = 'h', )

```


```{r inferences.A, cache = TRUE}

adjbrick <- adj.catadata.list$adjbrick
# Bootstrapping
bootCA.adj <- Boot4PTCA(ZeDataCube = adjbrick,
                        fi = FIsym.adj,
                        fj = FJs.adj,
                        eigs = CAEigs.adj,
                        nf2keep = 3,
                        nBootIter = 500)
# Compute Bootstrapped ratios
bootRatadj.I <- PTCA4CATA::boot.ratio.test(bootCA.adj$RowsBoot,
                                            critical.value = 2)
bootRatadj.J <- PTCA4CATA::boot.ratio.test(bootCA.adj$ColumnsBoot,
                                              critical.value = 2)
# Probabilities 
probBRadj.I  <- bootRatadj.I$prob.boot.ratios
probBRadj.J  <- bootRatadj.J$prob.boot.ratios

# Permutation tests
#adjca.inf <- perm4PTCA(aCube = adjbrick,
#                       nIter = 1000,
#                       permType = 'byRows' ,
#                       Malinvaud = TRUE)
#Ind.Permu.adj    <- adjca.inf$permInertia
#InertiaFixed.adj <- adjca.inf$fixedInertia
#prob.cpt.lst.adj <- adjca.inf$MalinvaudQ['p-perm',]
## Get the p values for the components
#prob.cpt.adj <- (unlist(prob.cpt.lst.adj[2:length(prob.cpt.lst.adj)]))
#prob.cpt.adj[is.na(prob.cpt.adj)] <- 1
```



```{r HCA.adj}
D <- dist(FIsym.adj, method = "euclidean")
fit <- hclust(D)
ngroups <- 4
col4extree <- wes_palette("Darjeeling1", ngroups, type = "continuous")
ex.groups <- cutree(fit, k= ngroups)
col4exgrp <- recode(ex.groups, 
                    "1" = col4extree[1],
                    "2" = col4extree[2],
                    "3" = col4extree[3],
                    "4" = col4extree[4])

col4extree <- col4exgrp[fit$order]
mus.tree4excerpts <- factoextra::fviz_dend(fit,  k = ngroups, 
                        k_colors = unique(col4extree), 
                        label_cols = col4extree,
                        cex = .75, xlab = 'Excerpts', rect = T,
                        rect_fill = T, main = " ") + theme(plot.title = element_text(size = 16, family = "serif"),
                      axis.title = element_text(size = 14, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 14, face = "italic", family = "serif"))
 


#main = 'Hierarchical Cluster Analysis: Excerpts, Adjectives Survey'

mus.tree4excerpts
```


```{r HCA4words}

D.w <- dist(t(adj.contingency), method = "euclidean")
fit.w <- hclust(D.w, method = "ward.D2")
fit.w3 <- kmeans(adjsym.cares$ExPosition.Data$fj, 5)
fit.w2 <- kmeans(t(adj.contingency), 5)

ngroups <- 4

col4wordtree <- c(wesanderson::wes_palettes$Royal2[1],
                  wesanderson::wes_palettes$Rushmore1[3:5],
                  wesanderson::wes_palettes$Royal1[1])
                  

word.groups <- cutree(fit.w, k= ngroups)

col4words <- recode(word.groups,#,fit.w3$cluster, 
                    "1" = col4wordtree[1],
                    "2" = col4wordtree[2],
                    "3" = col4wordtree[3],
                    "4" = col4wordtree[4])
                   # "5" = col4wordtree[5])
                    #"6" = col4wordtree[6])

#col4words <- col4words[fit.w$order]

cols$adj.gc <- unique(col4words)
cols$adj.oc <- col4words

tree4words <- factoextra::fviz_dend(fit.w,  k = ngroups, 
                              k_colors = unique(col4words[fit.w$order]), 
                              label_cols = col4words[fit.w$order],
                        cex = .5, xlab = 'Adjectives', rect = T, rect_fill = T, 
                        main = " ") + theme(plot.title = element_text(size = 16, family = "serif"),
                      axis.title = element_text(size = 14, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 14, face = "italic", family = "serif"))
                         
 
#main = "Hierarchical Cluster Analysis, using Ward's Distance: Adjectives")

                        
tree4words
```

```{r symmetricmap, fig.show = 'hold', out.width='100%', fig.height=10}

rownames(FIsym.adj) <- c(1:16,18:30)

fifjadj <- rbind(FIsym.adj[,1:2], FJs.adj[,1:2])

colorsij <- abind(cols$ex.oc, cols$adj.oc, along = 1)

pchvec <- c(rep("19", dim(FIsym.adj)[1]), rep("18", dim(FJs.adj)[1]))

axisone <- 1
axistwo <- 2

adjmap4repel <- createFactorMap(fifjadj,
                                axis1 = axisone,axis2 = axistwo
                                , col.points = colorsij
                                , col.labels = colorsij
                                , text.cex = 5
                                , cex = 3
 #                               , pch = pchvec
                                )




adjmap.sym <- createFactorMapIJ(FIsym.adj,
                                FJs.adj,
                                axis1 = axisone,axis2 = axistwo,
                                col.points.i = cols$ex.oc, 
                                col.labels.i = cols$ex.oc, 
                                col.points.j = cols$adj.oc, 
                                col.labels.j = cols$adj.oc,
                                text.cex.i = 5, text.cex.j = 5,
                                cex.i = 3, cex.j = 3
                                )

vc.sym.labels <- createxyLabels(resCA = adjsym.cares)
mus.adj.005 <- adjmap.sym$baseMap +  adjmap.sym$I_points + 
            adjmap.sym$I_labels + adjmap.sym$J_points + 
              adjmap.sym$J_labels + vc.sym.labels + 
                ggtitle(' ') + theme(plot.title = element_text(size = 16, family = "serif"),
                      axis.title = element_text(size = 16, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 16, face = "italic", family = "serif"))

mus.adj.repel <- adjmap4repel$zeMap + vc.sym.labels + theme(plot.title = element_text(size = 16, family = "serif"),
                      axis.title = element_text(size = 16, face = "italic", family = "serif"))
  
print(mus.adj.005)
print(mus.adj.repel)
```


```{r contributions}

signed.ctrI.adj <- adjsym.cares$ExPosition.Data$ci*-1 * sign(FIsym.adj)
signed.ctrJ.adj <- adjsym.cares$ExPosition.Data$cj*-1 * sign(FJs.adj)

# plot contributions of rows for component 1
ctradjI.1 <- PrettyBarPlot2(signed.ctrI.adj[,1],
                         threshold = 1 / NROW(signed.ctrI.adj),
                         font.size = 3,
                         color4bar = cols$ex.oc[order(signed.ctrI.adj[,1])] , # we need hex code
                         ylab = 'Signed Contributions', sortValues = TRUE,
                         ylim = c(1.2*min(signed.ctrI.adj[,1]), 1.2*max(signed.ctrI.adj[,1]))
) + ggtitle("Component 1", subtitle = 'Rows')  + theme(plot.title = element_text(size = 16, family = "serif"),
                      axis.title = element_text(size = 14, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 14, face = "italic", family = "serif"))

# plot contributions of columns for component 1
ctradjJ.1 <- PrettyBarPlot2(signed.ctrJ.adj[,1],
                         threshold = 1 / NROW(signed.ctrJ.adj),
                         font.size = 3,
                         color4bar = cols$adj.oc[order(signed.ctrJ.adj[,1])], # we need hex code
                         ylab = 'Signed Contributions', sortValues = TRUE,
                         ylim = c(1.2*min(signed.ctrJ.adj[,1]), 1.2*max(signed.ctrJ.adj[,1]))
) + ggtitle("", subtitle = 'Columns')  + theme(plot.title = element_text(size = 16, family = "serif"),
                      axis.title = element_text(size = 14, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 14, face = "italic", family = "serif"))

# plot contributions of rows for component 2
ctradjI.2 <- PrettyBarPlot2(signed.ctrI.adj[,2],
                         threshold = 1 / NROW(signed.ctrI.adj),
                         font.size = 3,
                         color4bar = cols$ex.oc[order(signed.ctrI.adj[,2])], # we need hex code
                         ylab = 'Signed Contributions', sortValues = TRUE,
                         ylim = c(1.2*min(signed.ctrI.adj[,2]), 1.2*max(signed.ctrI.adj[,2]))
) + ggtitle("Component 2", subtitle = 'Rows')  + theme(plot.title = element_text(size = 16, family = "serif"),
                      axis.title = element_text(size = 14, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 14, face = "italic", family = "serif"))

# plot contributions of columns for component 2
ctradjJ.2 <- PrettyBarPlot2(signed.ctrJ.adj[,2],
                         threshold = 1 / NROW(signed.ctrJ.adj),
                         font.size = 3,
                         color4bar = cols$adj.oc[order(signed.ctrJ.adj[,2])], # we need hex code
                         ylab = 'Signed Contributions', sortValues = TRUE,
                         ylim = c(1.2*min(signed.ctrJ.adj[,2]), 1.2*max(signed.ctrJ.adj[,2]))
) + ggtitle("", subtitle = 'Columns')  + theme(plot.title = element_text(size = 16, family = "serif"),
                      axis.title = element_text(size = 14, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 14, face = "italic", family = "serif"))

```

```{r thecons, fig.width=14}

grid.arrange(
    as.grob(ctradjI.1),as.grob(ctradjJ.1),
    as.grob(ctradjI.2),as.grob(ctradjJ.2),
    ncol = 2,nrow = 2
  )

Ctradj.IJ <- recordPlot()
```

# Supplementary materials: Experiment 3

```{r plscsetupsup}
library(TExPosition)
library(TInPosition)
library(data4PCCAR)
library(corrplot)


dimcontingency <- catadata.list$contingency
adjcontingency <- adj.catadata.list$adjcontingency

dimcontingency <- dimcontingency[-c(6,14,17),-9]
adjcontingency <- adjcontingency[-c(6,14),]

```


```{r covariance.mat, fig.height=14}
# Compute the correlation matrix
XY.cor <- cor(dimcontingency, adjcontingency)
# Plot it with corrplot
corrplot(XY.cor, method = "color", addCoefasPercent = TRUE, tl.cex = 1.25) 

a0.residuals <- recordPlot()

```

```{r plscressup}

pls.res <- tepPLS(dimcontingency, adjcontingency, DESIGN = adj.design$thedesign[-c(6,14)])
resPerm4PLSC <- perm4PLSC(dimcontingency, adjcontingency, nIter = 1000)


```


```{r barplotplscprepsup, fig.width=14}

ps <- pls.res$TExPosition.Data$pdq$p
ps <- ps[order(rownames(ps)),]

col4cols <- col4cols[-9] 

col4cols <- col4cols[order(rownames(ps))]

qs <- pls.res$TExPosition.Data$pdq$q
```


```{r loadingbarplotplscsup, fig.width=20, fig.height=14}

loading1p <- PrettyBarPlot2(bootratio = ps[,1], 
                       threshold = min(.6*max(abs(ps[,1]))), 
                       ylim = c(1.2*min(ps[,1]), 1.2*max(ps[,1])),
                       color4bar = c(col4cols),
                       color4ns = "gray75", 
                       plotnames = TRUE, 
#                       main = 'Loadings for Musical Qualities for LV1', 
                       ylab = "Signed Loadings"
#                      , horizontal = F
                      , font.size = 4
                       ) + ggtitle("Loadings for LV1", subtitle = 'Musical Qualities') + theme(plot.title = element_text(size = 20, family = "serif"),
                      axis.title = element_text(size = 18, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 18, face = "italic", family = "serif"))

loading1q <- PrettyBarPlot2(bootratio = qs[,1], 
                       threshold = min( .6*max(abs(qs[,1]))), 
                       ylim = c(1.2*min(qs[,1]), 1.2*max(qs[,1])),
                       color4bar = cols$adj.oc,
                       color4ns = "gray75", 
                       plotnames = TRUE, 
#                       main = 'Loadings for Adjectives for LV1', 
                       ylab = "Signed Loadings"
                       , font.size = 4
                       ) + ggtitle("", subtitle = 'Adjectives') + theme(plot.title = element_text(size = 20, family = "serif"),
                      axis.title = element_text(size = 18, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 18, face = "italic", family = "serif"))

loading2p <- PrettyBarPlot2(bootratio = ps[,2], 
                       threshold = min(.6*max(abs(ps[,2]))), 
                       ylim = c(1.2*min(ps[,2]), 1.2*max(ps[,2])),
                       color4bar = col4cols,
                       color4ns = "gray75", 
                       plotnames = TRUE, 
 #                      main = 'Loadings for Musical Qualities for LV2', 
                       ylab = "Signed Loadings"
#                       , horizontal = F
                       , font.size = 4
                       ) + ggtitle("Loadings for LV2", subtitle = 'Musical Qualities') + theme(plot.title = element_text(size = 20, family = "serif"),
                      axis.title = element_text(size = 18, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 18, face = "italic", family = "serif"))

loading2q <- PrettyBarPlot2(bootratio = qs[,2], 
                       threshold = min(.6*max(abs(qs[,2]))), 
                       ylim = c(1.2*min(qs[,2]), 1.2*max(qs[,2])),
                       color4bar = cols$adj.oc,
                       color4ns = "gray75", 
                       plotnames = TRUE, 
#                       main = 'Loadings for Adjectives for LV2', 
                       ylab = "Signed Loadings"
                      , font.size = 4
                       ) + ggtitle(" ", subtitle = 'Adjectives') + theme(plot.title = element_text(size = 20, family = "serif"),
                      axis.title = element_text(size = 18, face = "italic", family = "serif"),
                      plot.subtitle = element_text(size = 18, face = "italic", family = "serif"))


grid.arrange(
                      as.grob(loading1p), as.grob(loading1q),
                      as.grob(loading2p), as.grob(loading2q),
                      ncol = 2,nrow = 2
                      )



```
